services:
  postgres:
    image: ankane/pgvector:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=graphrag
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - graphrag-net

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./data/input:/app/data/input
      - ./data/output:/app/data/output
    environment:
      - PYTHONUNBUFFERED=1
      - POSTGRES_HOST=postgres
    networks:
      - graphrag-net

networks:
  graphrag-net:
    driver: bridge

volumes:
  pgdata: {}