services:
  app:
    build: .
    depends_on:
      - postgres
    environment:
      - DB_CONN_STRING=postgresql://postgres:admin@postgres:5432/graphrag
    volumes:
      - .:/app
    command: ["python", "scripts/run_indexing.py"]

  postgres:
    image: ankane/pgvector:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=graphrag
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"

volumes:
  pgdata: