paths:
  input_dir: "data/input"
  output_dir: "data/output"

llm:
  api_key: ${LLM_API_KEY}
  endpoint: "https://api.groq.com/openai/v1/chat/completions"

chunking:
  chunk_size: 512
  overlap: 50

db:
  conn_string: "postgresql://postgres:admin@localhost:5432/graphrag"
